version: "3.5"
services:
  postgres:
    image: "postgres:13.4-alpine"
    command:
      [
        "-c",
        "max_connections=2000",
        "-c",
        "effective_cache_size=25600MB",
        "-c",
        "work_mem=2MB",
        "-c",
        "wal_buffers=1MB",
        "-c",
        "synchronous_commit=off",
      ]
    volumes:
      - ~/.dockerdata/gobest/postgres:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}