version: "3.9"
services:
  postgres:
    image: "postgres:16-alpine3.18"
    command:
      [
        "-c",
        "max_connections=2000",
        "-c",
        "effective_cache_size=25600MB",
        "-c",
        "work_mem=2MB",
        "-c",
        "wal_buffers=1MB",
        "-c",
        "synchronous_commit=off",
      ]
    volumes:
      - ~/.dockerdata/gotemplate/postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ~/.dockerdata/gotemplate/redis-data:/var/lib/redis
      - ~/.dockerdata/gotemplate/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}